print reason of failure if could not download iso uri
Because archlinux changed its repo location, the current md5 uri
returns a 301 moved permanently message. Then using .body.split on it
made the iso and iso_md5 variables be nil. And then veewee choked on
that.

Before this commit, this is the actual message you get in this case:

  TypeError: no implicit conversion of nil into String
  veewee/lib/veewee/provider/core/helper/iso.rb:113:in `join'
  veewee/lib/veewee/provider/core/helper/iso.rb:113:in `verify_iso'
  veewee/lib/veewee/provider/core/box/build.rb:101:in `build'
  veewee/lib/veewee/provider/virtualbox/box/build.rb:10:in `build'
  veewee/lib/veewee/command/vbox.rb:22:in `build'
  ...

This commit actually makes the error message explicit:

  Could not instantiate the box mesh with provider Virtualbox ,Error in the definition from file veewee/definitions/mesh/definition.rb
  Could not download from http://mirrors.kernel.org/archlinux/iso/latest/md5sums.txt: [301] #<Net::HTTPMovedPermanently:0x007fe277b9e9c8>
  Error in the definition from file veewee/definitions/mesh/definition.rb
  Could not download from http://mirrors.kernel.org/archlinux/iso/latest/md5sums.txt: [301] #<Net::HTTPMovedPermanently:0x007fe277b9e9c8>